// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveBase64File(arg1, arg2) {
  return window['go']['main']['App']['SaveBase64File'](arg1, arg2);
}

export function SaveFileDialogWrapper(arg1) {
  return window['go']['main']['App']['SaveFileDialogWrapper'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}
