// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SaveBase64File(arg1:string,arg2:string):Promise<string>;

export function SaveFileDialogWrapper(arg1:main.SaveDialogOptiosWrapper):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;
